android:
  ota_zip: firmware/T18FL3__703000765AA_MOD_SW_02.09.00_+_CHIME_+_VR_+_DSP_+_MAPS/T18FL3_703000765AA_MOD_SW_02.09.00_+_CHIME_+_VR_+_DSP_+_MAPS.zip
  boot_img: Development/Chery_Emulator/payload/boot.img
  system_img: Development/Chery_Emulator/payload/system.img
  vendor_img: Development/Chery_Emulator/payload/vendor.img
  product_img: Development/Chery_Emulator/payload/product.img
  boot_partition: boot_b
  system_partition: system_b
  vendor_partition: vendor_b
qnx:
  ota_zip: firmware/T18FL3__703000765AA_MOD_SW_02.09.00_+_CHIME_+_VR_+_DSP_+_MAPS/T18FL3_703000765AA_MOD_SW_02.09.00_+_CHIME_+_VR_+_DSP_+_MAPS.zip
  qnx_boot_img: Development/Chery_Emulator/payload/qnx_boot.img
  qnx_system_img: Development/Chery_Emulator/payload/qnx_system.img
  boot_partition: qnx_boot_b
  system_partition: qnx_system_b
  enable: false
qemu:
  binary: Development/Chery_Emulator/qemu_g6sh/qemu-system-aarch64
  machine: g6sh
  dtb: Development/Chery_Emulator/qemu_g6sh/g6sh-emu.dtb
graphics:
  hu:
    vnc_host: 127.0.0.1
    vnc_port: 5900
  cluster:
    vnc_host: 127.0.0.1
    vnc_port: 5901
